image: "sseemayer/rust-musl-builder-mingw:latest"

stages:
  - test
  - build

#test:
#  stage: test
#  script:
#  - rustc --version && cargo --version
#  - cargo test --all --verbose

.build: &build
  stage: build
  artifacts:
    paths:
      - target/$TARGET/release/bcalm-viewer$EXT
  script:
    - cargo build --target $TARGET --release -- $ARGS


linux-musl-64:
  variables:
    TARGET: x86_64-unknown-linux-musl
  <<: *build

windows-mingw-64:
  variables:
    TARGET: x86_64-pc-windows-gnu
    EXT: .exe
  <<: *build

linux-musl-32:
  variables:
    TARGET: i686-unknown-linux-musl
  before_script:
    - &target rustup target add $TARGET
  <<: *build

windows-mingw-32:
  variables:
    TARGET: i686-pc-windows-gnu
    EXT: .exe
  before_script: [*target]
  <<: *build

macos-64:
  variables:
    TARGET: x86_64-apple-darwin
    OSX_VERSION: "10.10"
    OSX_VERSION_MIN: "10.7"
  before_script:
    - sudo apt install wget
    #- sudo apt install clang gcc g++
    #- sudo apt install zlib1g-dev libmpc-dev libmpfr-dev libgmp-dev
    - *target
    - git clone https://github.com/tpoechtrager/osxcross
    - cd osxcross
    - wget -nc https://s3.dockerproject.org/darwin/v2/MacOSX$OSX_VERSION.sdk.tar.xz
    - mv MacOSX$OSX_VERSION.sdk.tar.xz tarballs/
    - UNATTENDED=yes ./build.sh
    - cd ..
    - export PATH="$(pwd)/osxcross/target/bin:$PATH"
    - export LIBZ_SYS_STATIC=1
    - export CC=o64-clang
    - export CXX=o64-clang++
  <<: *build